variables: variables.yml

templates:
  tv:
    quality: 720p|1080p HDTV|bluray
    exists_series:
      - '/data/serier/{{series_name}}'
    set:
      path: /data/serier/{{series_name}}/Season {{series_season}}
    regexp:
      reject_excluding:
        - DKsubs|NORDiC|danish|DANiSH|Danish

  tv-queue-request:
    template: tv
    configure_series:
      from:
        trakt_list:
          username: ninstaah
          list: serier
          type: shows
      settings:
        propers: no

tasks:
  film:
    priority: 1
    trakt_list:
      account: ninstaah
      list: film
      type: movies
    accept_all: yes
    list_add:
      - movie_list: film_list 

  film_dl:
    priority: 2
    rss: '{? rss.db.film-rapidcows ?}'
    quality: 1080p
    imdb_lookup: yes
    list_match:
      from:
        - movie_list: film_list
    rtorrent:
      uri: scgi://localhost:5000
      path: /data/film/

  serier_tv:
    priority: 3
    template: tv-queue-request
    rss: '{? rss.db.tv ?}'
    rtorrent:
      uri: scgi://localhost:5000

  serier_tv_dansk:
    priority: 4
    template: tv-queue-request
    rss: '{? rss.db.tv-dansk ?}'
    rtorrent:
      uri: scgi://localhost:5000

  serier_tv_dbretail:
    priority: 5
    template: tv-queue-request
    rss: '{? rss.db.tv-dbretail ?}'
    rtorrent:
      uri: scgi://localhost:5000

  serier_tv_substance:
    priority: 6
    template: tv-queue-request
    rss: '{? rss.db.tv-substance ?}'
    rtorrent:
      uri: scgi://localhost:5000
  
schedules:
  - tasks: [film_dl, serier_tv, serier_tv_dansk, serier_tv_dbretail, serier_tv_substance, ]
    interval:
      minutes: 15
  - tasks: [film]
    interval:
      hours: 1