variables: variables.yml

templates:
  global:
    retry_failed:
      max_retries: 3
    seen: local

  dk_subs:
    require_field: series_name
    exists_series: '/data/serier/{{series_name}}'
    series:
      settings:
        720p:
          identified_by: ep
          set:
            path: /data/serier/{{ series_name }}/Season {{ series_season }}/
        1080p:
          identified_by: ep
          set:
            path: /data/serier/{{ series_name }}/Season {{ series_season }}/
      720p:
        - Eksempel Navn
      1080p:
        - Eksempel Navn
    regexp:
      reject_excluding:
        - DKsubs|NORDiC

  dk_tale:
    require_field: series_name
    series:
      settings:
        720p:
          identified_by: ep
          set:
            path: /data/serier/{{ series_name }}/Season {{ series_season }}/
        1080p:
          identified_by: ep
          set:
            path: /data/serier/{{ series_name }}/Season {{ series_season }}/
      720p:
        - Eksempel Navn
      1080p:
        - Eksempel Navn
    regexp:
      reject_excluding:
        - danish|DANiSH|Danish

tasks:
  sync-series:
    priority: 1
    manual: yes
    filesystem:
      path:
        - /data/serier/
      regexp: '.*\.(mp4|avi|mkv)$'
      recursive: yes
    disable: builtins
    configure_series:
      settings:
        set:
          tracking: no
      from:
        filesystem:
          - /data/serier/
    exec: echo "Found {{title}}"

  unrar-series:
    accept_all: yes
    parsing:
      series: guessit
    metainfo_series: yes
    require_field:
      - series_name
      - series_season
    filesystem:
      path: '/data/serier/'
      recursive: yes
      regexp: '.*\.(rar|zip)'
    decompress:
      to: '/data/serier/{{series_name}}/Season {{series_season}}/'
      keep_dirs: no
      delete_archive: no

  watchlist:
    priority: 1
    trakt_list:
      account: ninstaah
      list: watchlist
      type: movies
    accept_all: yes
    seen: local
    list_add:
      - movie_list: film_list 
  film-rapidcows:
    priority: 2
    rss: '{? rss.db.film-rapidcows ?}'
    quality: 1080p
    imdb_lookup: yes
    list_match:
      from:
        - movie_list: film_list
    rtorrent:
      uri: scgi://localhost:5000
      path: /data/film/

  tv-substance:
    rss: '{? rss.db.tv-substance ?}'
    rtorrent:
      uri: scgi://localhost:5000
      path: /data/tmp
    template:
      - dk_subs

  tv-dbretail:
    rss: '{? rss.db.tv-dbretail ?}'
    rtorrent:
      uri: scgi://localhost:5000
      path: /data/tmp
    template:
      - dk_subs

  tv:
    rss: '{? rss.db.tv ?}'
    rtorrent:
      uri: scgi://localhost:5000
      path: /data/tmp
    template:
      - dk_subs

  dansk-tv:
    rss: '{? rss.db.tv-dansk ?}'
    rtorrent:
      uri: scgi://localhost:5000
      path: /data/tmp
    template:
      - dk_tale
  
schedules:
  - tasks: [tv-substance, tv-dbretail, tv, tv-dansk, film-rapidcows]
    interval:
      minutes: 15
  - tasks: [unrar-series, sync-series]
    interval:
      hours: 2