variables: variables.yml

templates:
  tv:
    quality: 720p|1080p
    exists_series:
      - '/data/serier/{{series_name}}'
    set:
      path: /data/serier/{{series_name}}/Season {{series_season}}
    regexp:
      reject_excluding:
        - DKsubs|NORDiC|danish|DANiSH|Danish

  tv-queue-request:
    template: tv
    configure_series:
      from:
        trakt_list:
          username: ninstaah
          account: ninstaah
          list: serier
          type: shows
      settings:
        propers: no

tasks:
  trakt:
    priority: 1
    trakt_list:
      username: ninstaah
      account: ninstaah
      list: film
      type: movies
    accept_all: yes
    list_add:
      - movie_list: film_list 

  rapidcows:
    priority: 2
    rss: '{? db.rapidcows ?}'
    quality: 1080p
    imdb_lookup: yes
    list_match:
      from:
        - movie_list: film_list
    rtorrent:
      uri: scgi://localhost:5000
      path: /data/film/

  dbretail:
    template: tv-queue-request
    rss: '{? db.dbretail ?}'
    rtorrent:
      uri: scgi://localhost:5000

  substance:
    template: tv-queue-request
    rss: '{? db.substance ?}'
    rtorrent:
      uri: scgi://localhost:5000

  dktv:
    template: tv-queue-request
    rss: '{? db.dktv ?}'
    rtorrent:
      uri: scgi://localhost:5000

  tv:
    template: tv-queue-request
    rss: '{? db.tv ?}'
    rtorrent:
      uri: scgi://localhost:5000

schedules:
  - tasks: [dbretail, substance, dktv, tv]
    interval:
      minutes: 15
  - tasks: [trakt, rapidcows]
    interval:
      hours: 1